### ISSUE TITLE
Changes to Onboarding

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-crisis#1]
- All content applies to all children. Parents are not asked child name, age, or gender. _This is unique to this deployment and should not impact the global ParentText-crisis templates_
- Users can select how they would like to receive the content (text, audio, video)

**Comment by fagiothree** [comment]
excluded steps as specified in content_index https://docs.google.com/spreadsheets/d/1M3ohkdFNWzYQdMBdlnPP2_pi3RttKGXAvCUBgYLvuHA/edit#gid=0
