### ISSUE TITLE
Different Multimedia Content Access for Tips and Pause

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-crisis#28]
In Crisis text, users will select what format they want to receive content (low/med/high), but this variable will not impact all modules. 

All modules/tips will be received as text and images with the exception of the optional video. 
Take a Pause will be differentiated based on the media selection made during onboarding.

**Comment by fagiothree** [comment]
replaced multimedia_tips_next block with tips_next in the definition of the crisis module structure in https://docs.google.com/spreadsheets/d/1hcH8pFdiHZN0UvZgyv3Zht9ARBTx-VXhNBI2o8L7fHU/edit#gid=308996192
