### ISSUE TITLE
Changes to Module/Lesson/Tip Delivery

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/parenttext-crisis#3]
Tips are delivered using the same template as modules/lessons with some exceptions: 
Flow proceeds as:
Pause>Intro>Importance>Quiz>Tips>Comics>Opt.Video>Congratulations
- Users begin each module by taking a pause. The data list needs to include an intro message, video and audio asset files, and 4 text fields. Suggestion to author “taking a pause” moments in a separate data list, which can be shared easily across apps/chatbots. The field in the module data list can be a referral to a pause_id. 
- An additional video asset is made available before the home activity. ALL parents, regardless of selected content format, are asked if they would like to receive an additional video (video_query). Response NO triggers the in-module congratulations message. Response YES triggers the delivery of a video (video_intro; video_file_name). 
- If comics appear in a module/lesson, they will appear after the tips.

**Comment by fagiothree** [comment]
The following steps are needed:
- [ ] #4 
- [ ] #5 
- [ ] Create block template for additional optional video
- [ ] Define sequence of blocks for crisis modules
- [ ] Replace each first daily interaction with take a pause
- [ ] Remove illustration from course and program completion congrats
- [ ]
