### ISSUE TITLE
Create safeguarding file

### ISSUE THREAD

**Issue by fagiothree** [IDEMSInternational/parenttext-crisis#36]
https://docs.google.com/spreadsheets/d/1yz4z_SpNkBVvle9jbpHcGTwlol9UJfJMMmLp4hcSLdQ/edit?usp=sharing spreadsheet with translated keywords and triggers

**Comment by fagiothree** [comment]
- [ ] violence missing?
- [ ] check translation of triggers
- [ ] add french transaltion to english start trigger

**Comment by edmoss345** [comment]
@fagiothree the sheet for violence was missing in the original google sheet, I have added a placeholder in the excel file and resynced. I have also made a copy of the excel file on the IDEMS google drive, may be easiest to share this back with the local team if they need to add the translations for violence.

https://docs.google.com/spreadsheets/d/1DTzEDa1wWP06X4Pe3iUYQglNvLdBH2J7/edit?usp=sharing&ouid=106690810498272552744&rtpof=true&sd=true

Could you expand on the other points around triggers, from what I can see in the excel they look ok to me? Or do we need others?

**Comment by fagiothree** [comment]
* I checked with Laurie and violence should not be included
* The translation of some triggers was not consistent with this previous version shared https://docs.google.com/spreadsheets/d/1QxkFWdy56WDHopeHysRVDpEJdDA_b_dKFVQqaMCftrU/edit#gid=234854502
* in the START tab, the English row needs to have also the French translation because the trigger to join is sent before setting the language and otherwise the French version would not be recognised
